### ISSUE TITLE
Move "View Image" to middle of context menu, not top?

### ISSUE THREAD

**Issue by NurioHin** [agoupinets/view-image-context-menu-item#14]
Quick and easy question: Is it at all possible to move the "View Image" option to the middle of the context menu (where previously the "Open Image in New Tab" option was), instead of the very top? I don't mind having to do some fiddling for it

**Comment by agoupinets** [comment]
Hello,

> Is it at all possible to move the "View Image" option to the middle of the context menu

Yes, but its super fiddly. 

I'll start off by saying I'm not an expert around userChrome, but here's my head on approach:
Its possible to use `-moz-box-ordinal-group` to specify the render order of any menu item.
https://developer.mozilla.org/en-US/docs/Web/CSS/box-ordinal-group


I've peeked at the ids of various context menus (image and link, but there are a ton others)
![context-image-url-ids](https://user-images.githubusercontent.com/49403902/123462704-a1c9fc80-d5b8-11eb-99bc-7a12ba3ce86c.png)

if you are willing to take the ordering of the entire menu into your hands, userChrome.css like this works pretty well (may still need some tweaking):
My approach was to set the default group to 100, the addon's group to 50, and then everything i needed to be above it to 30
```css
/**
 * set the default for the group to be 100 instead of 1 as the spec
 * dictacts that the value should be a positive integer and we need to
 * group things before 1:
 * https://developer.mozilla.org/en-US/docs/Web/CSS/box-ordinal-group
 * 
 * userChrome.css cannot override the actual order of the items in the
 * html that backs context menu, but -moz-box-ordinal-group can change
 * they way its rendered (this will mess up arrow key movement)
 */
menupopup#contentAreaContextMenu > * { -moz-box-ordinal-group: 100; }

/* the following items are typically present if the media is wrapped in a link */
menuitem#context-openlinkintab { -moz-box-ordinal-group: 30 !important; }
menu#context-openlinkinusercontext-menu { -moz-box-ordinal-group: 30 !important; }
menuitem#context-openlink { -moz-box-ordinal-group: 30 !important; }
menuitem#context-openlinkprivate { -moz-box-ordinal-group: 30 !important; }
menuseparator#context-sep-open { -moz-box-ordinal-group: 30 !important; }
menuitem#context-bookmarklink { -moz-box-ordinal-group: 30 !important; }
menuitem#context-savelink { -moz-box-ordinal-group: 30 !important; }
menuitem#context-copylink { -moz-box-ordinal-group: 30 !important; }
menuseparator#context-sep-sendlinktodevice { -moz-box-ordinal-group: 30 !important; }

/* the following items are typically present if the media is an image*/
/*
menuitem#context-viewimage { -moz-box-ordinal-group: 100 !important; }
menuitem#context-saveimage { -moz-box-ordinal-group: 100 !important; }
menuitem#context-copyimage-contents { -moz-box-ordinal-group: 100 !important; }
menuitem#context-copyimage { -moz-box-ordinal-group: 100 !important; }
menuitem#context-sendimage { -moz-box-ordinal-group: 100 !important; }
menuitem#context-viewimageinfo { -moz-box-ordinal-group: 100 !important; }
menuseparator#context-sep-setbackground { -moz-box-ordinal-group: 100 !important; }
menuitem#context-setDesktopBackground { -moz-box-ordinal-group: 100 !important; }
*/

/* the following are inspect items */
/*
menuseparator#context-sep-ctp { -moz-box-ordinal-group: 100 !important; }
menuitem#context-inspect-a11y { -moz-box-ordinal-group: 100 !important; }
menuitem#context-inspect { -moz-box-ordinal-group: 100 !important; }
*/

/* this is the menu seperator that is usually present to seperate addons */
/*
menuseparator#context-media-eme-separator { -moz-box-ordinal-group: 100 !important; }
*/

/**
 * setting the group to be 50:
 * all menu sibling with group less than 50 will be shown above
 * all menu sibling with group more than 50 will be shown below
 * all menu sibling with group equal to 50 will be shown in the order of the html
 * (note: above css sets all default group values to be 100)
 * 
 * note: using CSS selectors as the full ids are very long:
 * _0d20e3ac-ee5b-4db9-bd3f-8ed745f569a7_-menuitem-_view-image-context-menu-item
 * _0d20e3ac-ee5b-4db9-bd3f-8ed745f569a7_-menuitem-_view-video-context-menu-item
 * _0d20e3ac-ee5b-4db9-bd3f-8ed745f569a7_-menuitem-_view-audio-context-menu-item
 */
menuitem[id*="view-image-context-menu-item"] { -moz-box-ordinal-group: 50 !important; }
menuitem[id*="view-video-context-menu-item"] { -moz-box-ordinal-group: 50 !important; }
menuitem[id*="view-audio-context-menu-item"] { -moz-box-ordinal-group: 50 !important; }



/* Hides Open Image In New Tab and Open Video In New Tab*/
#context-viewimage { display: none; }
#context-viewvideo { display: none; }

/* Hides the View menu item icons */
menuitem[id*="view-video-context-menu-item"] > .menu-iconic-left { opacity: 0 !important; }
menuitem[id*="view-audio-context-menu-item"] > .menu-iconic-left { opacity: 0 !important; }
menuitem[id*="view-image-context-menu-item"] > .menu-iconic-left { display: none !important; }

/* Alternative CSS to hide icon if not using Proton UI (old UI pads differently) */
/*
menuitem[id*="view-image-context-menu-item"] > .menu-iconic-left { visibility: hidden !important; }
*/
```
What the CSS looks like:
![image](https://user-images.githubusercontent.com/49403902/123468002-2f104f80-d5bf-11eb-9ea3-7ba8df8d988c.png)
