### ISSUE TITLE
Instructions for moving "View Image" to the top are no longer working

### ISSUE THREAD

**Issue by notfood** [agoupinets/view-image-context-menu-item#16]
Firefox: 113.0 Linux

Apparently the context menu changed structure, now using the userChrome workaround can't no longer move it outside of the "addons" block which is at the very end.
```css
/* Moves View Image to the very top */
menuitem[id*="view-image-context-menu-item"] { -moz-box-ordinal-group: 0 !important; }
```

I've been fiddling with it without much success, any suggestion?

**Comment by notfood** [comment]
Managed to fix it with the following:
```css
/* Moves View Image to the very top */
menuitem[id*="view-image-context-menu-item"] { order: -1 !important; }
```

Apparently `-moz-box-ordinal-group` no longer exists. I'm speculating, I don't know. I'll leave the issue open as the instructions are not correct anymore.

**Comment by agoupinets** [comment]
Thanks for the issue - `-moz-box-ordinal-group` was already marked as deprecated at the time so im not too surprised that its been dropped. But as the menu is using flex, order should be the way to go. I've updated the addon's description with the following CSS which references both properties for now:
```css
#context-viewimage,
#context-viewvideo { display: none; }

/* uncomment this if you want to hide a bunch of other somewhat useless menu items
#context-openlinkintab,
#context-openlink,
#context-bookmarklink,
#context-sendimage,
#context-sep-setbackground,
#context-setDesktopBackground,
#context-inspect-a11y { display: none; }
*/

menupopup#contentAreaContextMenu > * { -moz-box-ordinal-group: 100; }

menuitem#context-openlinkintab,
menu#context-openlinkinusercontext-menu,
menuitem#context-openlink,
menuitem#context-openlinkprivate,
menuseparator#context-sep-open,
menuitem#context-bookmarklink,
menuitem#context-savelink,
menuitem#context-copylink,
menuseparator#context-sep-sendlinktodevice { -moz-box-ordinal-group: 30 !important; order: -20 !important; }

/**
* note: using CSS selectors as the full ids are very long:
* _0d20e3ac-ee5b-4db9-bd3f-8ed745f569a7_-menuitem-_view-image-context-menu-item
* _0d20e3ac-ee5b-4db9-bd3f-8ed745f569a7_-menuitem-_view-video-context-menu-item
* _0d20e3ac-ee5b-4db9-bd3f-8ed745f569a7_-menuitem-_view-audio-context-menu-item
*/
menuitem[id*="view-image-context-menu-item"],
menuitem[id*="view-video-context-menu-item"],
menuitem[id*="view-audio-context-menu-item"] { -moz-box-ordinal-group: 50 !important; order: -10 !important; }

menuitem[id*="view-video-context-menu-item"] > .menu-iconic-left { opacity: 0 !important; }
menuitem[id*="view-audio-context-menu-item"] > .menu-iconic-left { opacity: 0 !important; }
menuitem[id*="view-image-context-menu-item"] > .menu-iconic-left { display: none !important; }
/* really old ui: menuitem[id*="view-image-context-menu-item"] > .menu-iconic-left { visibility: hidden !important; } */
```
the CSS also includes hiding the image and moving the view image item to where the open image in new tab was.
technically, since `-moz-box-ordinal-group` does nothing post-113, this can be pared down to only:
```css
#context-viewimage,
#context-viewvideo { display: none; }

/* uncomment this if you want to hide a bunch of other somewhat useless menu items
#context-openlinkintab,
#context-openlink,
#context-bookmarklink,
#context-sendimage,
#context-sep-setbackground,
#context-setDesktopBackground,
#context-inspect-a11y { display: none; }
*/

menuitem#context-openlinkintab,
menu#context-openlinkinusercontext-menu,
menuitem#context-openlink,
menuitem#context-openlinkprivate,
menuseparator#context-sep-open,
menuitem#context-bookmarklink,
menuitem#context-savelink,
menuitem#context-copylink,
menuseparator#context-sep-sendlinktodevice { order: -20 !important; }

/**
* note: using CSS selectors as the full ids are very long:
* _0d20e3ac-ee5b-4db9-bd3f-8ed745f569a7_-menuitem-_view-image-context-menu-item
* _0d20e3ac-ee5b-4db9-bd3f-8ed745f569a7_-menuitem-_view-video-context-menu-item
* _0d20e3ac-ee5b-4db9-bd3f-8ed745f569a7_-menuitem-_view-audio-context-menu-item
*/
menuitem[id*="view-image-context-menu-item"],
menuitem[id*="view-video-context-menu-item"],
menuitem[id*="view-audio-context-menu-item"] { order: -10 !important; }

menuitem[id*="view-video-context-menu-item"] > .menu-iconic-left { opacity: 0 !important; }
menuitem[id*="view-audio-context-menu-item"] > .menu-iconic-left { opacity: 0 !important; }
menuitem[id*="view-image-context-menu-item"] > .menu-iconic-left { display: none !important; }
/* really old ui: menuitem[id*="view-image-context-menu-item"] > .menu-iconic-left { visibility: hidden !important; } */
```

of course hiding the icon or the actual ordering can be adjusted to the user's liking
