### ISSUE TITLE
Move "Open Image in New Tab" under "View Image"

### ISSUE THREAD

**Issue by kirbco** [agoupinets/view-image-context-menu-item#22]
Spent quite a while on this but couldn't figure it out. 

First, I was just trying to get "Open Image in New Tab" back. After an hour I finally realized all I had to do was remove this part at the top.

![Image](https://github.com/user-attachments/assets/c4746755-e6e7-4db4-8ea0-740a2b202c7d)

And now when I open/click on an image it appears right under "View Image," like I wanted to.

![Image](https://github.com/user-attachments/assets/9f69da4b-1fd6-4aac-a04a-78f5ff5cea2e)

But when I right click from far away, without opening the image, "Open Imagine in New Tab" appears under "Copy Link Without Site Tracking" and "Send to Device" instead of directly under "View Image". 

![Image](https://github.com/user-attachments/assets/652b3216-25cf-4a10-b517-1eadf90c04b1)

It's not like a huge deal but I would like it to appear under "View Image" even when I haven't opened the image. Here's what my Chrome css looks like btw:

![Image](https://github.com/user-attachments/assets/7906c0ea-f193-4d6b-b4eb-d0a4b02343c1)

**Comment by agoupinets** [comment]
Hello, the context menu has changed a bit since i originally wrote the chrome CSS. Your issue stems from the addition of two items (Copy Link Without Site Tracking and Send Link to Device) that are not being sorted because the original CSS i provided was written before they were added.

Taking another look, for example, this is the default current menu in FF 134 when i right click an image on X/Twitter:

![Image](https://github.com/user-attachments/assets/a29f76aa-8b03-4074-a152-7394b5cf49b7)

Peeking at the HTML that builds that menu, its something like the code block below. I've stripped out number of inner tags and other properties outside of name/label/hidden/disabled (so this isn't exactly what the HTML for the menu is, just the important parts).

This HTML contains *a lot* (all?) possible menu items, outside of what is shown for the context menu when right clicking and image that is a link - the options that aren't shown are `hidden="true"`, depending on what is right clicked. Add-on `menuitem`s seem to be created/destroyed rather than shown/hidden when the menu is shown, and i've omitted them here.
```html
<menupopup id="contentAreaContextMenu">
	<menugroup id="context-navigation" hidden="true">
		<menuitem id="context-back" class="menuitem-iconic"></menuitem>
		<menuitem id="context-forward" class="menuitem-iconic" disabled="true"></menuitem>
		<menuitem id="context-reload" class="menuitem-iconic" hidden="true"></menuitem>
		<menuitem id="context-stop" class="menuitem-iconic" hidden="true" disabled="true"></menuitem>
		<menuitem id="context-bookmarkpage" class="menuitem-iconic" hidden="true"></menuitem>
	</menugroup>
	<menuseparator id="context-sep-navigation" hidden="true"/>
	<menuitem id="context-viewsource-goToLine" hidden="true"></menuitem>
	<menuitem id="context-viewsource-wrapLongLines" type="checkbox" hidden="true"></menuitem>
	<menuitem id="context-viewsource-highlightSyntax" type="checkbox" hidden="true"></menuitem>
	<menuseparator id="context-sep-viewsource-commands" hidden="true"/>
	<menuitem id="spell-no-suggestions" disabled="true" label="No Spelling Suggestions" hidden="true"></menuitem>
	<menuitem id="spell-add-to-dictionary" label="Add to Dictionary" hidden="true"></menuitem>
	<menuitem id="spell-undo-add-to-dictionary" label="Undo Add To Dictionary" hidden="true"></menuitem>
	<menuseparator id="spell-suggestions-separator" hidden="true"/>
	<menuitem id="context-openlinkincurrent" class="context-menu-open-link" label="Open Link" hidden="true"></menuitem>
	<menuitem id="context-openlinkincontainertab" class="context-menu-open-link" label="Open Link in New  Tab" hidden="true"></menuitem>
	<menuitem id="context-openlinkintab" class="context-menu-open-link" label="Open Link in New Tab"></menuitem>
	<menu id="context-openlinkinusercontext-menu" class="context-menu-open-link" label="Open Link in New Container Tab">
		<menupopup id="context-openlinkinusercontext-popup" hasbeenopened="true">
			<menuitem class="menuitem-iconic identity-color-blue identity-icon-fingerprint" label="Personal"></menuitem>
			<menuitem class="menuitem-iconic identity-color-orange identity-icon-briefcase" label="Work"></menuitem>
			<menuitem class="menuitem-iconic identity-color-green identity-icon-dollar" label="Banking"></menuitem>
			<menuitem class="menuitem-iconic identity-color-pink identity-icon-cart" label="Shopping"></menuitem>
		</menupopup>
	</menu>
	<menuitem id="context-openlink" class="context-menu-open-link" label="Open Link in New Window"></menuitem>
	<menuitem id="context-openlinkprivate" class="context-menu-open-link" label="Open Link in New Private Window"></menuitem>
	<menuseparator id="context-sep-open"/>
	<menuitem id="context-bookmarklink" label="Bookmark Link…"></menuitem>
	<menuitem id="context-savelink" label="Save Link As…"></menuitem>
	<menuitem id="context-savelinktopocket" label="Save Link to Pocket"></menuitem>
	<menuitem id="context-copyemail" label="Copy Email Address" hidden="true"></menuitem>
	<menuitem id="context-copyphone" label="Copy Phone Number" hidden="true"></menuitem>
	<menuitem id="context-copylink" label="Copy Link"></menuitem>
	<menuitem id="context-stripOnShareLink" label="Copy Link Without Site Tracking" disabled="true"></menuitem>
	<menu id="context-sendlinktodevice" class="sync-ui-item" hidden="true" label="Send Link to Device">
		<menupopup id="context-sendlinktodevice-popup"/>
	</menu>
	<menuseparator id="context-sep-sendlinktodevice" class="sync-ui-item"/>
	<menuseparator id="context-sep-copylink" hidden="true"/>
	<menuitem id="context-media-play" label="Play" disabled="false" hidden="true"></menuitem>
	<menuitem id="context-media-pause" label="Pause" hidden="true" disabled="false"></menuitem>
	<menuitem id="context-media-mute" label="Mute" disabled="false" hidden="true"></menuitem>
	<menuitem id="context-media-unmute" label="Unmute" hidden="true" disabled="false"></menuitem>
	<menu id="context-media-playbackrate" label="Speed" disabled="false" hidden="true">
		<menupopup>
			<menuitem id="context-media-playbackrate-050x" type="radio" name="playbackrate" label="0.5×" checked="false" disabled="false"></menuitem>
			<menuitem id="context-media-playbackrate-100x" type="radio" name="playbackrate" checked="true" label="1.0×" disabled="false"></menuitem>
			<menuitem id="context-media-playbackrate-125x" type="radio" name="playbackrate" label="1.25×" checked="false" disabled="false"></menuitem>
			<menuitem id="context-media-playbackrate-150x" type="radio" name="playbackrate" label="1.5×" checked="false" disabled="false"></menuitem>
			<menuitem id="context-media-playbackrate-200x" type="radio" name="playbackrate" label="2×" checked="false" disabled="false"></menuitem>
		</menupopup>
	</menu>
	<menuitem id="context-media-loop" type="checkbox" label="Loop" checked="false" hidden="true"></menuitem>
	<menuitem id="context-leave-dom-fullscreen" label="Exit Full Screen" hidden="true"></menuitem>
	<menuitem id="context-video-fullscreen" label="Full Screen" disabled="false" hidden="true"></menuitem>
	<menuitem id="context-media-hidecontrols" label="Hide Controls" disabled="false" hidden="true"></menuitem>
	<menuitem id="context-media-showcontrols" label="Show Controls" hidden="true" disabled="false"></menuitem>
	<menuseparator id="context-media-sep-video-commands" hidden="true"/>
	<menuitem id="context-viewvideo" label="Open Video in New Tab" disabled="false" hidden="true"></menuitem>
	<menuitem id="context-video-pictureinpicture" type="checkbox" label="Watch in Picture-in-Picture" checked="false" disabled="false" hidden="true"></menuitem>
	<menuseparator id="context-media-sep-commands" hidden="true"/>
	<menuitem id="context-reloadimage" label="Reload Image" hidden="true"></menuitem>
	<menuitem id="context-viewimage" label="Open Image in New Tab"></menuitem>
	<menuitem id="context-saveimage" label="Save Image As…"></menuitem>
	<menuitem id="context-video-saveimage" label="Take Snapshot…" disabled="false" hidden="true"></menuitem>
	<menuitem id="context-savevideo" label="Save Video As…" disabled="false" hidden="true"></menuitem>
	<menuitem id="context-saveaudio" label="Save Audio As…" hidden="true" disabled="false"></menuitem>
	<menuitem id="context-copyimage-contents" label="Copy Image"></menuitem>
	<menuitem id="context-copyimage" label="Copy Image Link"></menuitem>
	<menuitem id="context-copyvideourl" label="Copy Video Link" disabled="false" hidden="true"></menuitem>
	<menuitem id="context-copyaudiourl" label="Copy Audio Link" hidden="true" disabled="false"></menuitem>
	<menuitem id="context-sendimage" label="Email Image…"></menuitem>
	<menuitem id="context-sendvideo" label="Email Video…" disabled="false" hidden="true"></menuitem>
	<menuitem id="context-sendaudio" label="Email Audio…" hidden="true" disabled="false"></menuitem>
	<menuitem id="context-imagetext" label="Copy Text From Image" hidden="true"></menuitem>
	<menuitem id="context-viewimageinfo" hidden="true" label="View Image Info" disabled="false"></menuitem>
	<menuitem id="context-viewimagedesc" label="View Description" hidden="true"></menuitem>
	<menuseparator id="context-sep-setbackground"/>
	<menuitem id="context-setDesktopBackground" label="Set Image as Desktop Background…"></menuitem>
	<menuseparator id="context-sep-sharing"/>
	<menuitem id="context-savepage" label="Save Page As…" hidden="true"></menuitem>
	<menuitem id="context-pocket" label="Save Page to Pocket" hidden="true"></menuitem>
	<menu id="context-sendpagetodevice" class="sync-ui-item" hidden="true" label="Send Page to Device">
		<menupopup id="context-sendpagetodevice-popup"/>
	</menu>
	<menu id="fill-login" hidden="true">
		<menupopup id="fill-login-popup"/>
	</menu>
	<menuitem id="fill-login-generated-password" hidden="true" label="Suggest Strong Password…" disabled="false"></menuitem>
	<menuitem id="use-relay-mask" hidden="true" label="Use Relay Email Mask"></menuitem>
	<menuitem id="manage-saved-logins" hidden="true" label="Manage Passwords"></menuitem>
	<menuseparator id="passwordmgr-items-separator" ensureHidden="true" hidden="true"/>
	<menuitem id="context-undo" label="Undo" hidden="true" disabled="true"></menuitem>
	<menuitem id="context-redo" label="Redo" hidden="true" disabled="true"></menuitem>
	<menuseparator id="context-sep-redo" hidden="true"/>
	<menuitem id="context-cut" label="Cut" hidden="true"></menuitem>
	<menuitem id="context-copy" label="Copy" hidden="true"></menuitem>
	<menuitem id="context-paste" label="Paste" hidden="true"></menuitem>
	<menuitem id="context-paste-no-formatting" label="Paste Without Formatting" hidden="true" disabled="true"></menuitem>
	<menuitem id="context-delete" label="Delete" hidden="true" disabled="true"></menuitem>
	<menuitem id="context-selectall" label="Select All" hidden="true"></menuitem>
	<menuitem id="context-pdfjs-highlight-selection" label="Highlight Selection" hidden="true"></menuitem>
	<menuitem id="context-reveal-password" type="checkbox" label="Reveal Password" hidden="true"></menuitem>
	<menuitem id="context-print-selection" label="Print Selection…" hidden="true"></menuitem>
	<menuseparator id="context-sep-selectall" hidden="true"/>
	<menuitem id="context-pdfjs-undo" label="Undo" hidden="true"></menuitem>
	<menuitem id="context-pdfjs-redo" label="Redo" hidden="true"></menuitem>
	<menuseparator id="context-sep-pdfjs-redo" hidden="true"/>
	<menuitem id="context-pdfjs-cut" label="Cut" hidden="true"></menuitem>
	<menuitem id="context-pdfjs-copy" label="Copy" hidden="true"></menuitem>
	<menuitem id="context-pdfjs-paste" label="Paste" hidden="true"></menuitem>
	<menuitem id="context-pdfjs-delete" label="Delete" hidden="true"></menuitem>
	<menuitem id="context-pdfjs-selectall" label="Select All" hidden="true"></menuitem>
	<menuseparator id="context-sep-pdfjs-selectall" hidden="true"/>
	<menuitem id="context-take-screenshot" label="Take Screenshot" hidden="true"></menuitem>
	<menuseparator id="context-sep-screenshots" hidden="true"/>
	<menuitem id="context-keywordfield" label="Add a Keyword for this Search…" hidden="true"></menuitem>
	<menuitem id="context-searchselect" label="Search DuckDuckGo for “Opens profile p…”" hidden="true"></menuitem>
	<menuitem id="context-searchselect-private" hidden="true"></menuitem>
	<menuitem id="context-translate-selection" label="Translate Link Text to English" target-language="en"></menuitem>
	<menu id="context-ask-chat" hidden="true">
	</menu>
	<menuseparator id="frame-sep"/>
	<menu id="frame" label="This Frame" hidden="true">
		<menupopup>
			<menuitem id="context-showonlythisframe" label="Show Only This Frame"></menuitem>
			<menuitem id="context-openframeintab" label="Open Frame in New Tab"></menuitem>
			<menuitem id="context-openframe" label="Open Frame in New Window"></menuitem>
			<menuseparator id="open-frame-sep"/>
			<menuitem id="context-reloadframe" label="Reload Frame"></menuitem>
			<menuseparator/>
			<menuitem id="context-bookmarkframe" label="Bookmark Frame…"></menuitem>
			<menuitem id="context-saveframe" label="Save Frame As…"></menuitem>
			<menuseparator/>
			<menuitem id="context-printframe" label="Print Frame…"></menuitem>
			<menuseparator/>
			<menuitem id="context-take-frame-screenshot" label="Take Screenshot"></menuitem>
			<menuseparator id="context-sep-frame-screenshot"/>
			<menuitem id="context-viewframesource" label="View Frame Source"></menuitem>
			<menuitem id="context-viewframeinfo" label="View Frame Info"></menuitem>
		</menupopup>
	</menu>
	<menuseparator id="spell-separator" hidden="true"/>
	<menuitem id="spell-check-enabled" type="checkbox" label="Check Spelling" hidden="true" checked="false"></menuitem>
	<menuitem id="spell-add-dictionaries-main" label="Add Dictionaries…" hidden="true"></menuitem>
	<menu id="spell-dictionaries" label="Languages" hidden="true">
		<menupopup id="spell-dictionaries-menu">
			<menuseparator id="spell-language-separator"/>
			<menuitem id="spell-add-dictionaries" label="Add Dictionaries…"></menuitem>
		</menupopup>
	</menu>
	<menuseparator hidden="true" id="context-sep-bidi"/>
	<menuitem hidden="true" id="context-bidi-text-direction-toggle" label="Switch Text Direction" disabled="true"></menuitem>
	<menuitem hidden="true" id="context-bidi-page-direction-toggle" label="Switch Page Direction"></menuitem>
	<menuseparator id="inspect-separator" hidden="true"/>
	<menuitem id="context-viewpartialsource-selection" label="View Selection Source" hidden="true"></menuitem>
	<menuitem id="context-viewsource" label="View Page Source" hidden="true"></menuitem>
	<menuitem id="context-inspect-a11y" label="Inspect Accessibility Properties"></menuitem>
	<menuitem id="context-inspect" label="Inspect"></menuitem>
	<menuseparator id="context-media-eme-separator"/>
	<menuitem id="context-media-eme-learnmore" class="menuitem-iconic" hidden="true" label="Learn more about DRM…"></menuitem>
</menupopup>
```

As end users or add-on developers, we do not get to control what Mozilla puts into the menu and in what order or what the menu items are identified as, but by using userChrome.css, we can apply CSS styling to that menu. With our custom CSS we can hide menu items and apply a visual sort order (which doesn't change the order of the HTML, but the order of how its rendered), which how the menu item can be moved around and the old menu item hidden in the CSS I've provided in the add-on description.

If you are looking to order menu items in a certain way, you can use the userChrome.css to apply the sort order on any of the ids given.
Filtering down the above list to only non-hidden items, shows the 24 `menuitem`s, `menu`s, and `menuseperator`s:
```html
<menupopup id="contentAreaContextMenu">
	<menuitem id="context-openlinkintab" class="context-menu-open-link" label="Open Link in New Tab"></menuitem>
	<menu id="context-openlinkinusercontext-menu" class="context-menu-open-link" label="Open Link in New Container Tab"></menu>
	<menuitem id="context-openlink" class="context-menu-open-link" label="Open Link in New Window"></menuitem>
	<menuitem id="context-openlinkprivate" class="context-menu-open-link" label="Open Link in New Private Window"></menuitem>
	<menuseparator id="context-sep-open"/>
	<menuitem id="context-bookmarklink" label="Bookmark Link…"></menuitem>
	<menuitem id="context-savelink" label="Save Link As…"></menuitem>
	<menuitem id="context-savelinktopocket" label="Save Link to Pocket"></menuitem>
	<menuitem id="context-copylink" label="Copy Link"></menuitem>
	<menuitem id="context-stripOnShareLink" label="Copy Link Without Site Tracking" disabled="true"></menuitem>
	<menuseparator id="context-sep-sendlinktodevice" class="sync-ui-item"/>
	<menuitem id="context-viewimage" label="Open Image in New Tab"></menuitem>
	<menuitem id="context-saveimage" label="Save Image As…"></menuitem>
	<menuitem id="context-copyimage-contents" label="Copy Image"></menuitem>
	<menuitem id="context-copyimage" label="Copy Image Link"></menuitem>
	<menuitem id="context-sendimage" label="Email Image…"></menuitem>
	<menuseparator id="context-sep-setbackground"/>
	<menuitem id="context-setDesktopBackground" label="Set Image as Desktop Background…"></menuitem>
	<menuseparator id="context-sep-sharing"/>
	<menuitem id="context-translate-selection" label="Translate Link Text to English" target-language="en"></menuitem>
	<menuseparator id="frame-sep"/>
	<menuitem id="context-inspect-a11y" label="Inspect Accessibility Properties"></menuitem>
	<menuitem id="context-inspect" label="Inspect"></menuitem>
	<menuseparator id="context-media-eme-separator"/>
</menupopup>
```
which can be identified in the CSS as
```css
menupopup#contentAreaContextMenu /*CONTEXT MENU CONTAINER*/
menuitem#context-openlinkintab /*Open Link in New Tab*/
menu#context-openlinkinusercontext-menu /*Open Link in New Container Tab*/
menuitem#context-openlink /*Open Link in New Window*/
menuitem#context-openlinkprivate /*Open Link in New Private Window*/
menuseparator#context-sep-open
menuitem#context-bookmarklink /*Bookmark Link…*/
menuitem#context-savelink /*Save Link As…*/
menuitem#context-savelinktopocket /*Save Link to Pocket*/
menuitem#context-copylink /*Copy Link*/
menuitem#context-stripOnShareLink /*Copy Link Without Site Tracking*/
menuseparator#context-sep-sendlinktodevice
menuitem#context-viewimage /*Open Image in New Tab*/
menuitem#context-saveimage /*Save Image As…*/
menuitem#context-copyimage-contents /*Copy Image*/
menuitem#context-copyimage /*Copy Image Link*/
menuitem#context-sendimage /*Email Image…*/
menuseparator#context-sep-setbackground
menuitem#context-setDesktopBackground /*Set Image as Desktop Background…*/
menuseparator#context-sep-sharing
menuitem#context-translate-selection /*Translate Link Text to English*/
menuseparator#frame-sep
menuitem#context-inspect-a11y /*Inspect Accessibility Properties*/
menuitem#context-inspect /*Inspect*/
menuseparator#context-media-eme-separator
```
Annoyingly, i dont see the "Send Link to Device" menu which you do - that would be identified by `menu#context-sendlinktodevice` and would also need to be sorted.

In your case, you wanted to see the menu items for "View Image" and "Open Image in New Tab", which could be achieved with CSS along the lines of:
```css
menuitem#context-openlinkintab, /*Open Link in New Tab*/
menu#context-openlinkinusercontext-menu, /*Open Link in New Container Tab*/
menuitem#context-openlink, /*Open Link in New Window*/
menuitem#context-openlinkprivate, /*Open Link in New Private Window*/
menuseparator#context-sep-open,
menuitem#context-bookmarklink, /*Bookmark Link…*/
menuitem#context-savelink, /*Save Link As…*/
menuitem#context-savelinktopocket, /*Save Link to Pocket*/
menuitem#context-copylink, /*Copy Link*/
menuitem#context-stripOnShareLink, /*Copy Link Without Site Tracking*/
menu#context-sendlinktodevice, /*Send Link to Device*/
menuseparator#context-sep-sendlinktodevice { order: -20 !important; }

menuitem[id*="view-image-context-menu-item"],
menuitem[id*="view-video-context-menu-item"],
menuitem[id*="view-audio-context-menu-item"] { order: -10 !important; }

menuitem[id*="view-video-context-menu-item"] > .menu-iconic-left { opacity: 0 !important; }
menuitem[id*="view-audio-context-menu-item"] > .menu-iconic-left { opacity: 0 !important; }
menuitem[id*="view-image-context-menu-item"] > .menu-iconic-left { display: none !important; }

```
Which would look like this:

![Image](https://github.com/user-attachments/assets/ffc978b0-c195-4069-881e-3c70a3d05da5)

I haven't extensively checked how the ordering would look for other menus with different subsets of menu items, like right clicking a non-link image, or a video. The sample CSS above also omits hiding any of the other menu items. You can pick and choose what you want to see by referencing the `id` of the menu item from the html blocks above. Also, only `order` needs to be specified in the CSS `-moz-box-ordinal-group` has been deprecated and no longer applies (i really need to update my sample CSS in the addon description).

Sorry for the wall of text, hopefully this makes sense and is a suitable reference.

TL;DR:
- using userChrome.css you can visually sort menu items by applying a numeric value for `order` - items are rendered from lowest to highest order value (so -20 for menu items you want to see first, -10 for the view image addon menu item, and the default 0 from everything after)
- menu items you dont want can be hidden by applying `display: none`
- you can reference `menuitem`, `menu`, and `menuseperator` elements by `id` from the HTML above.

![Image](https://github.com/user-attachments/assets/0cfa1710-7991-46dd-b6a6-fc3bdc7d95e6)

**Comment by agoupinets** [comment]
This is the `userChrome.css` that I've come up with based on the latest menu items. Hopefully this works universally for the current version of Firefox. I'll update the add-on description with this as the default. Note it hides a number of menu items - edit/remove parts of this CSS as desired.
```css
/*
  Based on context menu elements parsed from Firefox 124.
  Menu items change between Firefox releases. This CSS may be out of date.

  This CSS attempts to impose a visual sort order using the "order" style attribute.
  Elements are rendered in ascending order. It also styles the add-ons menu elements
  to look like the default ones by hiding the icon.

  Order:
  - All menu items fore "View Video" set as order: -40
  - "View Video" set as order: -30
  - All menu items after "View Video" but before "View Image" set as order: -20
  - "View Image" and "View Audio" set as order: -10
  - Everything after "View Image" and "Video Audio" is omitted and defaults to order: 0

  Styling:
  - View Image has its icon hidden
  - View Audio/Video has its icon made invisible (the padding needs to be a bit different)

  Hiding: OMIT OR EDIT THESE SECTIONS AS DESIRED
  - The original "Open Image in New Tab" menu elements are hidden
  - Optionally other elements, like "Email Image..." can be hidden if not need

*/


/* Style the add-on's menu elements to hide the icons */
menuitem[id*="view-video-context-menu-item"] > .menu-iconic-left { opacity: 0 !important; }
menuitem[id*="view-audio-context-menu-item"] > .menu-iconic-left { opacity: 0 !important; }
menuitem[id*="view-image-context-menu-item"] > .menu-iconic-left { display: none !important; }


/* All the menu elements below should be rendered BEFORE the add-on's "View Video" menu element */
menugroup#context-navigation,
menuseparator#context-sep-navigation,
menuitem#context-viewsource-goToLine,
menuitem#context-viewsource-wrapLongLines,
menuitem#context-viewsource-highlightSyntax,
menuseparator#context-sep-viewsource-commands,
menuitem#spell-no-suggestions, /* No Spelling Suggestions */
menuitem#spell-add-to-dictionary, /* Add to Dictionary */
menuitem#spell-undo-add-to-dictionary, /* Undo Add To Dictionary */
menuseparator#spell-suggestions-separator,
menuitem#context-openlinkincurrent, /* Open Link */
menuitem#context-openlinkincontainertab, /* Open Link in New  Tab */
menuitem#context-openlinkintab, /* Open Link in New Tab */
menu#context-openlinkinusercontext-menu, /* Open Link in New Container Tab */
menuitem#context-openlink, /* Open Link in New Window */
menuitem#context-openlinkprivate, /* Open Link in New Private Window */
menuseparator#context-sep-open,
menuitem#context-bookmarklink, /* Bookmark Link… */
menuitem#context-savelink, /* Save Link As… */
menuitem#context-savelinktopocket, /* Save Link to Pocket */
menuitem#context-copyemail, /* Copy Email Address */
menuitem#context-copyphone, /* Copy Phone Number */
menuitem#context-copylink, /* Copy Link */
menuitem#context-stripOnShareLink, /* Copy Link Without Site Tracking */
menu#context-sendlinktodevice, /* Send Link to Device */
menuseparator#context-sep-sendlinktodevice,
menuseparator#context-sep-copylink,
menuitem#context-media-play, /* Play */
menuitem#context-media-pause, /* Pause */
menuitem#context-media-mute, /* Mute */
menuitem#context-media-unmute, /* Unmute */
menu#context-media-playbackrate, /* Speed */
menuitem#context-media-loop, /* Loop */
menuitem#context-leave-dom-fullscreen, /* Exit Full Screen */
menuitem#context-video-fullscreen, /* Full Screen */
menuitem#context-media-hidecontrols, /* Hide Controls */
menuitem#context-media-showcontrols, /* Show Controls */
menuseparator#context-media-sep-video-commands
{ order: -40 !important; }


/* The add-on's "View Video" is rendered next */
menuitem[id*="view-video-context-menu-item"]
{ order: -30 !important; }


/* All the menu elements below should be rendered after the "View Video" but before "View Image" and "View Audio" */
menuitem#context-viewvideo, /* Open Video in New Tab */
menuitem#context-video-pictureinpicture, /* Watch in Picture-in-Picture */
menuseparator#context-media-sep-commands,
menuitem#context-reloadimage /* Reload Image */
{ order: -20 !important; }


/* The menu elements below are from the add-on and are rendered after the elements above */
menuitem[id*="view-image-context-menu-item"],
menuitem[id*="view-audio-context-menu-item"]
{ order: -10 !important; }


/* Rest of elements ommited; any menu element not in the above two selections will render below "View Image" */


/* Hide the original "View .. in New Tab" menu elements. Omit this section if want to keep old menu items too */
menuitem#context-viewvideo, /* Open Video in New Tab */
menuitem#context-viewimage /* Open Image in New Tab */
{ display: none; }


/* Optionally hide other menu items. Omit or edit this section as desired. */
menugroup#context-navigation,
menuseparator#context-sep-navigation,
menuitem#context-openlinkincurrent, /* Open Link */
menuitem#context-openlinkincontainertab, /* Open Link in New  Tab */
menuitem#context-openlinkintab, /* Open Link in New Tab */
menuitem#context-openlink, /* Open Link in New Window */
menuitem#context-openlinkprivate, /* Open Link in New Private Window */
menuseparator#context-sep-open,
menuitem#context-bookmarklink, /* Bookmark Link… */
menuitem#context-savelinktopocket, /* Save Link to Pocket */
menuitem#context-sendimage, /* Email Image… */
menuitem#context-sendvideo, /* Email Video… */
menuitem#context-sendaudio, /* Email Audio… */
menuseparator#context-sep-setbackground,
menuitem#context-setDesktopBackground /* Set Image as Desktop Background… */
{ display: none; }
```
