### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by sal0max** [agoupinets/view-image-context-menu-item#7]
Hi,
great plugin. Thanks for it!

How do you think about supporting localized strings in your plugin?
Seems pretty easy. E.g.:
- declared string: https://github.com/mdn/webextensions-examples/blob/master/menu-demo/_locales/en/messages.json#L17
- usage: https://github.com/mdn/webextensions-examples/blob/master/menu-demo/background.js#L40

That way your plugin could feel even more native.

I could supply german translation

**Comment by sal0max** [comment]
Actually, if you want to provide localization, you can just use *all* the localized strings like they used to be by using the value of the key `main-context-menu-image-view` in Mozillas source.

- Like e.g. German
   https://hg.mozilla.org/l10n-central/de/file/default/browser/browser/browserContext.ftl#l275
   -> "Grafik anzeigen"
- French:
   https://hg.mozilla.org/l10n-central/fr/file/default/browser/browser/browserContext.ftl#l275
   -> "Afficher l’image"
- Turkish:
   https://hg.mozilla.org/l10n-central/tr/file/default/browser/browser/browserContext.ftl#l275
   -> "Resme bak"

...

**Comment by agoupinets** [comment]
Seems reasonable, i'll give that a shot in the following version; note that will can break the userChrome.css which was based on the menu label.

new version that should be agnostic to the menu label provided in the addon's description:
```css
/* Moves View Image to the very top */
menuitem[id*="view-image-context-menu-item"] { -moz-box-ordinal-group: 0 !important; }

/* Moves View Video to the very top */
menuitem[id*="view-video-context-menu-item"] { -moz-box-ordinal-group: 0 !important; }
```
